worker-threads: 4
worker-fs-threads: 2
logger-level: debug

is_testing: true

server-port: 8080

# hello_postgres_db is the service name + _ + filename of the db.sql
dbconnection: 'postgresql://testsuite@localhost:15433/hello_postgres_db'
